/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class AdminDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardFrame
     */
    public AdminDashboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UpdateMedBtn = new javax.swing.JButton();
        RemoveMedBtn = new javax.swing.JButton();
        AddMedBtn = new javax.swing.JButton();
        viewOrdersbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Dashboard");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));

        UpdateMedBtn.setBackground(new java.awt.Color(204, 204, 255));
        UpdateMedBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateMedBtn.setText("Update Medicine");
        UpdateMedBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        UpdateMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMedBtnActionPerformed(evt);
            }
        });

        RemoveMedBtn.setBackground(new java.awt.Color(204, 204, 255));
        RemoveMedBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RemoveMedBtn.setText("Remove Medicine");
        RemoveMedBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        RemoveMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMedBtnActionPerformed(evt);
            }
        });

        AddMedBtn.setBackground(new java.awt.Color(204, 204, 255));
        AddMedBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddMedBtn.setText("Add Medicine");
        AddMedBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        AddMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedBtnActionPerformed(evt);
            }
        });

        viewOrdersbtn.setBackground(new java.awt.Color(204, 204, 255));
        viewOrdersbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewOrdersbtn.setText("View Orders");
        viewOrdersbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        viewOrdersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(RemoveMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(UpdateMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(viewOrdersbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateMedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewOrdersbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMedBtnActionPerformed
        // TODO add your handling code here:
        UpdateMedFrame updateMed = new UpdateMedFrame();
        updateMed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateMedBtnActionPerformed

    private void RemoveMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMedBtnActionPerformed
        // TODO add your handling code here:
        remove_MedFrame removeMed = new remove_MedFrame();
        removeMed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RemoveMedBtnActionPerformed

    private void AddMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedBtnActionPerformed
        // TODO add your handling code here:
        AddMedicineFrame addMedFrame = new AddMedicineFrame() ;
        addMedFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddMedBtnActionPerformed

    private void viewOrdersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersbtnActionPerformed
        // TODO add your handling code here:
        viewAllOrdersFrame ordersF = new viewAllOrdersFrame() ; 
        ordersF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewOrdersbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMedBtn;
    private javax.swing.JButton RemoveMedBtn;
    private javax.swing.JButton UpdateMedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewOrdersbtn;
    // End of variables declaration//GEN-END:variables
}
